### ISSUE TITLE
com.amazonaws.internal.keyvaluestore.KeyNotFoundException

### ISSUE THREAD

**Issue by nisargpro** [IoTReady/flutter-aws-iot#8]
I/flutter (24421): {USERNAME: nisarg, PASSWORD: nisarg@123, POLICY_NAME: test, REGION: AP_SOUTH_1, ENDPOINT: a2qjty4wsdd1fv-ats.iot.ap-south-1.amazonaws.com, CLIENT_ID: test}
D/PluginScaffold(24421): invoke { channel: com.pycampers.flutter_cognito_plugin, method: initialize(), args: null }
I/AWSKeyValueStore(24421): Detected Android API Level = 29
I/AWSKeyValueStore(24421): Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.mobile.client
I/AWSKeyValueStore(24421): Detected Android API Level = 29
I/AWSKeyValueStore(24421): Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.android.auth
W/LogFactory(24421): Truncating log tag length as it exceed 23, the limit imposed by Android on certain API Levels
I/AWSKeyValueStore(24421): Detected Android API Level = 29
I/AWSKeyValueStore(24421): Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.android.auth
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = ap-south-1:6dc14035-2bdc-4038-ad01-2299cbb9ca01.identityId
D/CognitoCachingCredentialsProvider(24421): Loading credentials from SharedPreferences
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = ap-south-1:6dc14035-2bdc-4038-ad01-2299cbb9ca01.expirationDate
D/CognitoCachingCredentialsProvider(24421): No valid credentials found in SharedPreferences
W/LogFactory(24421): Truncating log tag length as it exceed 23, the limit imposed by Android on certain API Levels
I/AWSKeyValueStore(24421): Detected Android API Level = 29
I/AWSKeyValueStore(24421): Creating the AWSKeyValueStore with key for sharedPreferencesForData = CognitoIdentityProviderCache
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = provider
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = token
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = cognitoIdentityId
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = isFederationEnabled
D/AWSMobileClient(24421): Inspecting user state details
D/PluginScaffold(24421): invoke { channel: com.pycampers.flutter_cognito_plugin, method: currentUserState(), args: null }
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = provider
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = token
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = cognitoIdentityId
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = isFederationEnabled
D/AWSMobileClient(24421): Inspecting user state details
D/PluginScaffold(24421): invoke { channel: com.pycampers.flutter_cognito_plugin, method: currentUserState(), args: null }
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = provider
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = token
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = cognitoIdentityId
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = isFederationEnabled
D/AWSMobileClient(24421): Inspecting user state details
I/flutter (24421): UserState.SIGNED_OUT
D/PluginScaffold(24421): invoke { channel: com.pycampers.flutter_cognito_plugin, method: isSignedIn(), args: null }
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = provider
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = token
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = cognitoIdentityId
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = isFederationEnabled
D/AWSMobileClient(24421): Inspecting user state details
D/PluginScaffold(24421): invoke { channel: com.pycampers.flutter_cognito_plugin, method: signIn(), args: {password=nisarg@123, username=nisarg} }
W/CognitoUserSession(24421): CognitoUserSession is not valid because idToken is null.
D/AWSMobileClient(24421): Sending password.
I/AWSKeyValueStore(24421): Detected Android API Level = 29
I/AWSKeyValueStore(24421): Creating the AWSKeyValueStore with key for sharedPreferencesForData = CognitoIdentityProviderDeviceCache.ap-south-1_10CxModKf.nisarg
I/DpmTcmClient(24421): RegisterTcmMonitor from: $Proxy0
V/com.amazonaws.request(24421): Parsing service response JSON
D/com.amazonaws.request(24421): CRC32Checksum = null
D/com.amazonaws.request(24421): content encoding = null
V/com.amazonaws.request(24421): Done parsing service response
V/com.amazonaws.request(24421): Parsing service response JSON
D/com.amazonaws.request(24421): CRC32Checksum = null
D/com.amazonaws.request(24421): content encoding = null
V/com.amazonaws.request(24421): Done parsing service response
I/flutter (24421): SignInResult { signInState: SignInState.NEW_PASSWORD_REQUIRED, parameters: {userAttributes: {"email_verified":"true","phone_number_verified":"true","phone_number":"+919611923911","email":"nisarghegadenisu@gmail.com"}, requiredAttributes: []}, userCodeDeliveryDetails: null }
D/PluginScaffold(24421): invoke { channel: com.pycampers.flutter_cognito_plugin, method: getIdentityId(), args: null }
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = ap-south-1:6dc14035-2bdc-4038-ad01-2299cbb9ca01.identityId
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = cognitoIdentityId
I/flutter (24421): null
D/PluginScaffold(24421): invoke { channel: com.pycampers.flutter_cognito_plugin, method: getIdentityId(), args: null }
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = ap-south-1:6dc14035-2bdc-4038-ad01-2299cbb9ca01.identityId
E/AWSKeyValueStore(24421): com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
I/AWSKeyValueStore(24421): Deleting the encryption key identified by the keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias
E/AWSKeyValueStore(24421): Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = cognitoIdentityId
E/flutter (24421): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: 'package:aws_iot/src/client.dart': Failed assertion: line 183 pos 12: 'identityId != null && policyName != null': is not true.
E/flutter (24421): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (24421): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (24421): #2      AWSIotDevice.attachPolicy (package:aws_iot/src/client.dart:183:12)
E/flutter (24421): #3      main (package:aws_iot_example/main.dart:23:16)
E/flutter (24421): <asynchronous suspension>

**Comment by ruchith696** [comment]
even i am facing same issue
